development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: picardrive_development
  username: powermike
  pool: 5
 
test: &test
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: picardrive_test
  username: powermike
  pool: 5
 
production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: picardrive_production
  username: powermike
  pool: 5
cucumber:
  <<: *test